[package]
name = "stackup-lint"
version = "0.1.0"
authors = ["stevesweetney <stevesweetney@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
graphql-parser = "0.2.3"